ERROR 2018-03-27 17:29:35,141 exception 5188 140215258966320 Internal Server Error: /mydata/csv_into_hive
Traceback (most recent call last):
  File "/home/taoshu/anaconda3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/taoshu/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taoshu/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taoshu/tzb_databrain/engine/db_engine/common/UTIL.py", line 47, in wrapper
    return func(*arg, **kwargs)
  File "/home/taoshu/tzb_databrain/engine/db_engine/db_engine/my_data.py", line 340, in csv_into_hive
    raise e
  File "/home/taoshu/tzb_databrain/engine/db_engine/db_engine/my_data.py", line 337, in csv_into_hive
    load_into_hive(hive_filename, new_csv_saving_path, hdfs_path, hdfs_path_dir, field_list)
  File "/home/taoshu/tzb_databrain/engine/db_engine/db_engine/my_data.py", line 113, in load_into_hive
    raise e
  File "/home/taoshu/tzb_databrain/engine/db_engine/db_engine/my_data.py", line 111, in load_into_hive
    func(table_name, csv_path, hdfs_path, hdfs_path_dir, ff)
  File "/home/taoshu/anaconda3/lib/python3.5/site-packages/py4j/java_gateway.py", line 1160, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/taoshu/anaconda3/lib/python3.5/site-packages/py4j/protocol.py", line 320, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o341.uploadToHive.
: java.lang.NullPointerException
	at com.taodatarobot.engine.py4j.hive.ObjectPool.release(ObjectPool.java:94)
	at com.taodatarobot.engine.py4j.hive.HiveUtil.uploadToHive(HiveUtil.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

